name: Weekly AI Radar

on:
  schedule:
    - cron: "0 7 * * 1"   # Mondays 07:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Generate latest.json
        env:
          # Optional: add a GitHub token secret to increase rate limits:
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TZ: "UTC"
        run: |
          python scripts/generate_report.py

      - name: Commit and push if changed
        run: |
          git config user.name "ai-radar-bot"
          git config user.email "ai-radar-bot@users.noreply.github.com"
          git add latest.json
          git commit -m "Weekly update: latest.json" || echo "No changes"
          git push
